apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  volumes:
  - name: shared
    emptyDir: {}

  containers:
  - name: my-container
    image: nginx:latest
    volumeMounts:
    - name: shared
      mountPath: /shared

  - name: busybox
    image: busybox
    command:
    - sh
    - -c
    - sleep 3600
    volumeMounts:
    - name: shared
      mountPath: /data








